services:
  cat-climber:
    image: ghcr.io/slmingol/cat-climber:latest
    ports:
      - "3992:80"
    restart: unless-stopped
    volumes:
      - puzzle-data:/puzzle-data

volumes:
  puzzle-data:
